CREATE DATABASE cadastro;
CREATE TABLE clientes (

id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL,
telefone VARCHAR(15) NOT NULL,
endereco VARCHAR(255) NOT NULL,
data_nascimento DATE NOT NULL
);